### 合并操作
___
numpy.concatenate((a1, a2, ...), axis=0, out=None)将向量拼接起来
___
Join a sequence of arrays along an existing axis.

In [1]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [2]:
x

array([1, 2, 3])

In [3]:
y

array([3, 2, 1])

In [4]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [5]:
z = np.array([666, 666, 666])

In [6]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [7]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [8]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([A, A], axis = None)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [10]:
np.concatenate([A, A], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
np.concatenate([A, A], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

可以将A矩阵表示有两个样本，每个样本有三个特征，z表示一个样本只有三个特征，
___
如何合并成一个样本?
___
可以看到A,z合并不了，这是因为他们是不同的维数，A是二维，z是一维

In [13]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

我们可以将z向量用reshape转换成二维的矩阵，reshape(1, -1)表示一行n列，n是根据元素个数计算的

In [14]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [15]:
A2 = np.concatenate([A, z.reshape(1, -1)])

In [16]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

numpy.vstack()垂直方向上堆叠，行智能
_________
numpy.hstack()水平方线上对的，列智能

In [17]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [18]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [25]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

###  分割操作
___
numpy.split(ary, indices_or_sections, axis=0)
___
axis如果是1，从第二维分割

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ary[:3]/ary[3:5]/ary[5:]

In [38]:
x1, x2, x3 = np.split(x, [3, 5])

In [29]:
x1

array([0, 1, 2])

In [40]:
x2

array([3, 4])

In [41]:
x3

array([5, 6, 7, 8, 9])

In [43]:
x1, x2 = np.split(x, [5])

In [44]:
x1

array([0, 1, 2, 3, 4])

In [45]:
x2

array([5, 6, 7, 8, 9])

In [47]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
A1, A2 = np.split(A, [2])

In [55]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
A1, A2 = np.split(A, [2], axis = 1)

In [58]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [59]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [63]:
upper, lower = np.vsplit(A, [2])

In [65]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [66]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
left, right = np.hsplit(A, [2])

In [68]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [69]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

下面是4x4矩阵，可能代表有4个样本，每个样本有三个特征，
___
最后一列代表的是每个样本对应的目标值(类别或者连续的数字)
___
可能要将特征矩阵与label向量分割开的需求,可以使用水平分割hsplit

In [71]:
data = np.arange(16).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
x, y = np.hsplit(data, [-1])
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [77]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

行抽出所有行，列只针对第0列，形成一个行向量

In [79]:
y[:, 0]

array([ 3,  7, 11, 15])