### 合并操作
___
numpy.concatenate((a1, a2, ...), axis=0, out=None)将向量拼接起来
___
Join a sequence of arrays along an existing axis.

In [1]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [2]:
x

array([1, 2, 3])

In [3]:
y

array([3, 2, 1])

In [9]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [10]:
z = np.array([666, 666, 666])

In [12]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [19]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [22]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
np.concatenate([A, A], axis = None)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [24]:
np.concatenate([A, A], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
np.concatenate([A, A], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])