### 聚合操作


In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.54853502, 0.64104084, 0.67688159, 0.00394012, 0.90558954,
       0.43441704, 0.00755616, 0.69155115, 0.7494321 , 0.77379373,
       0.14808999, 0.33708905, 0.9721298 , 0.08876855, 0.08846794,
       0.95440565, 0.6857847 , 0.08860001, 0.11536939, 0.49244141,
       0.3799203 , 0.15936619, 0.78765597, 0.55790413, 0.28257388,
       0.75233414, 0.70668448, 0.4302951 , 0.14536518, 0.10830562,
       0.55084293, 0.00224961, 0.84192362, 0.4824813 , 0.62765514,
       0.61213431, 0.65823445, 0.56705035, 0.31913737, 0.56289383,
       0.63466766, 0.67754943, 0.89399498, 0.46394905, 0.01184631,
       0.54075436, 0.65417467, 0.52250547, 0.66952387, 0.64234084,
       0.71534571, 0.27731685, 0.74759564, 0.40753874, 0.7845138 ,
       0.89485853, 0.09264253, 0.73779512, 0.26737204, 0.69548632,
       0.58829216, 0.8999861 , 0.05036999, 0.18891977, 0.8127876 ,
       0.69349752, 0.92340803, 0.44360631, 0.02855004, 0.95037879,
       0.54532194, 0.95482829, 0.68808284, 0.87918378, 0.56536

Py3中的内置函数(built-in function)sum()和numpy中array
sum函数区别就在于效率

In [3]:
sum(L)

52.23410369687291

In [4]:
np.sum(L)

52.2341036968729

In [5]:
L.sum()

52.2341036968729

In [6]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)
%timeit np.ndarray.sum(big_array)
%timeit big_array.sum()

573 ms ± 58.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.77 ms ± 317 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.26 ms ± 57.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.33 ms ± 432 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


求矩阵中元素的最小值和最大值
a.min()/a.max()

In [7]:
np.min(big_array)

3.4370311807752074e-07

In [8]:
np.max(big_array)

0.9999982362701092

In [9]:
big_array.min()

3.4370311807752074e-07

In [10]:
big_array.max()

0.9999982362701092

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis = 0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis = 1)

array([ 6, 22, 38, 54])

numpy.prod(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)
___
Return the product of array elements over a given axis.

In [15]:
np.prod(X)

0

In [16]:
np.prod(X + 1)

2004189184

numpy.mean()求最小值
___
numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)[source]

In [17]:
np.mean(X)

7.5

numpy.median求中位数
___
numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)[source]

In [18]:
np.median(X)

7.5

统计学中中位数更好的比平均值描述样本

In [19]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
___
数据不同百分位置的值

In [21]:
np.percentile(big_array, q = 50)

0.499476511284293

In [22]:
np.percentile(big_array, q = 100)

0.9999982362701092

In [23]:
np.max(big_array)

0.9999982362701092

In [24]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, percent))

3.4370311807752074e-07
0.25003404113416244
0.499476511284293
0.750135794654795
0.9999982362701092


求矩阵的方差numpy.var
___
numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)
____
求标准差numpy.std
___
numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)

In [25]:
np.var(big_array)

0.08330528804363813

In [26]:
np.std(big_array)

0.28862655464048714

In [27]:
np.power(np.var(big_array), 1/2)

0.28862655464048714

In [28]:
x = np.random.normal(0, 1, size = 1000000)

In [29]:
np.mean(x)

0.0003534893831371255

In [30]:
np.std(x)

0.9999816156478893

### 索引

In [31]:
x

array([-0.36375058,  0.47041706,  0.53211324, ...,  0.94300753,
        0.88077272, -0.19280283])

In [33]:
np.min(x)

-4.767271169523922

In [34]:
np.argmin(x)

656339

In [36]:
np.argmax(x)

949968

In [37]:
x[np.argmax(x)]

4.583302491736498

In [38]:
np.max(x)

4.583302491736498

### 排序和使用索引

In [42]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### shuffle方法对数组进行乱序排序

In [41]:
np.random.shuffle(x)
x

array([ 4,  5, 11,  7, 13,  1,  6, 12,  2,  0,  3, 15,  9,  8, 14, 10])

In [43]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### 对x本身进行排序

In [45]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
X = np.random.randint(10, size=(4,4))
X

array([[8, 0, 1, 9],
       [1, 8, 8, 3],
       [3, 6, 1, 6],
       [7, 4, 1, 8]])

In [47]:
np.sort(X, axis=1)

array([[0, 1, 8, 9],
       [1, 3, 8, 8],
       [1, 3, 6, 6],
       [1, 4, 7, 8]])

In [49]:
np.sort(X, axis=0)

array([[1, 0, 1, 3],
       [3, 4, 1, 6],
       [7, 6, 1, 8],
       [8, 8, 8, 9]])

In [50]:
np.sort(X, axis=-1)

array([[0, 1, 8, 9],
       [1, 3, 8, 8],
       [1, 3, 6, 6],
       [1, 4, 7, 8]])

In [53]:
np.random.shuffle(x)
x

array([ 5, 13,  6, 15,  7, 11, 10,  4,  8,  2, 12,  3, 14,  1,  0,  9])

In [54]:
np.argsort(x)

array([14, 13,  9, 11,  7,  0,  2,  4,  8, 15,  6,  5, 10,  1, 12,  3],
      dtype=int64)

In [56]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5, 10, 13,  8, 11, 12,  7, 14, 15,  6,  9])

### 可以看到是对应np.partition(x,3)的数组元素在初始数组中的下标

In [57]:
np.argpartition(x, 3)

array([13, 14,  9, 11,  7,  0,  6,  1,  8,  5, 10,  4, 12,  3,  2, 15],
      dtype=int64)

In [58]:
X

array([[8, 0, 1, 9],
       [1, 8, 8, 3],
       [3, 6, 1, 6],
       [7, 4, 1, 8]])

In [60]:
np.argsort(X, axis=1)

array([[1, 2, 0, 3],
       [0, 3, 1, 2],
       [2, 0, 1, 3],
       [2, 1, 0, 3]], dtype=int64)

In [73]:
np.argpartition(X, 2, axis = -1)

array([[1, 2, 0, 3],
       [0, 3, 2, 1],
       [2, 0, 1, 3],
       [2, 1, 0, 3]], dtype=int64)

In [72]:
np.partition(X, 2, axis = -1)

array([[0, 1, 8, 9],
       [1, 3, 8, 8],
       [1, 3, 6, 6],
       [1, 4, 7, 8]])

In [83]:
np.partition(X, 2, axis = 0)

array([[1, 0, 1, 3],
       [3, 4, 1, 6],
       [7, 6, 1, 8],
       [8, 8, 8, 9]])

In [82]:
np.argpartition(X, 2, axis = -1)

array([[1, 2, 0, 3],
       [0, 3, 2, 1],
       [2, 0, 1, 3],
       [2, 1, 0, 3]], dtype=int64)