In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ndarray.reshape(shape, order='C')
___
Returns an array containing the same data with a new shape.

In [3]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 数组的基本属性

ndarray.ndim数组的维数

In [4]:
x.ndim

1

In [5]:
X.ndim

2

ndarray.shape 返回的是一个元组，表示每个维度的数组大小,元组的长度是维数
n行m列矩阵，返回的是(n, m)

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

ndarray.size 数组的总元素个数。

In [9]:
x.size

10

In [10]:
X.size

15

### numpy.array的数据访问

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[0]

0

In [14]:
x[-1]

9

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

建议使用下面的形式访问多维数组的元素，不要使用X[0][0]
___
numpy数组类似Python序列类型支持切片

In [18]:
X[2, 2]

12

In [19]:
x[0:5]

array([0, 1, 2, 3, 4])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[::2]

array([0, 2, 4, 6, 8])

In [27]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

下面两个方块索引二元数组，取前两行前三列出错,要使用,运算符

In [35]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

访问矩阵前两行，从头到尾间隔为2的元素

In [38]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

从行倒着数，列倒着数访问

In [39]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [42]:
X[::, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])

In [41]:
X[::, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])

只取第一行

In [43]:
X[0, :]

array([0, 1, 2, 3, 4])

In [44]:
X[0]

array([0, 1, 2, 3, 4])

只取第一列

In [56]:
X[:, 0]

array([ 0,  5, 10])

在Python中使用切片是重新创建了一个全新矩阵；
___
但是在numpy中，切片后改变切片矩阵，原矩阵也要改变
因为numpy注重效率，使用浅拷贝

In [58]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [59]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [71]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
Y = X

In [73]:
X[0, 0] = 0

In [74]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

深拷贝,copy(),可以看到SubX变化，X没发生变化

In [75]:
subX = X[:2, :3].copy()

In [76]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [77]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

reshape

In [79]:
x.shape

(10,)

In [80]:
x.ndim

1

In [81]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

B是二维数组只有一行，每行都有10列，x为有10个元素一维的向量

In [89]:
B.ndim

2

In [90]:
B.shape

(1, 10)

In [91]:
x.shape

(10,)

x.reshape(10, -1)得到一个10行的元素的二维矩阵,

In [92]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [99]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])