## Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

### 如果想要访问不等间距的元素

In [5]:
x[3],x[5],x[8]

(3, 5, 8)

In [6]:
ind = [3, 5, 8]

#### 索引数组不仅可以使一维数组，也可以是二维数组
___
#### x[ind] ind为二维数组 ,返回的是是每行对应的索引位置的元素组成的二维数组

In [7]:
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([[0,2],
               [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

#### 可以选择二维矩阵中指定的坐标的点

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [11]:
X[row, col]

array([ 1,  6, 11])

In [12]:
X[0, col]

array([1, 2, 3])

In [13]:
X[-1, col]

array([13, 14, 15])

In [14]:
X[:, col]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

### 前两行的对应col列的数据

In [15]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
col = [1, 0, 1, 1]
X[1:3, col]

array([[5, 4, 5, 5],
       [9, 8, 9, 9]])

### 可以看到col是一个布尔数组
___
### True表示取对应的列，False表示不取，
___
### 因此结果是前两行的0、2、3列

In [17]:
col = [True, False, True, True]
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [30]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [32]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [34]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [37]:
X 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 获得4*4的布尔矩阵

In [38]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [40]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### 求布尔矩阵的为True的元素

In [43]:
np.sum(x <= 3)

4

In [45]:
True == 1

True

In [47]:
False == 0

True

True + True + True

### count_nonzero可以计算矩阵中非0元素的个数

In [49]:
np.count_nonzero(x <= 3)

4