## Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

### 如果想要访问不等间距的元素

In [5]:
x[3],x[5],x[8]

(3, 5, 8)

In [6]:
ind = [3, 5, 8]

#### 索引数组不仅可以使一维数组，也可以是二维数组
___
#### x[ind] ind为二维数组 ,返回的是是每行对应的索引位置的元素组成的二维数组

In [7]:
x[ind]

array([3, 5, 8])

In [11]:
ind = np.array([[0,2],
               [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

#### 可以选择二维矩阵中指定的坐标的点

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [19]:
X[row, col]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
X[0, col]

array([1, 2, 3])

In [23]:
X[-1, col]

array([13, 14, 15])